package com.jing.java.example.test;

import java.io.Serializable;

public class user implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_act_consume_task.uid
     *
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_act_consume_task.task_id
     *
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_act_consume_task.num
     *
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_act_consume_task.create_time
     *
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_act_consume_task.update_time
     *
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_act_consume_task.uid
     *
     * @return the value of user_act_consume_task.uid
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_act_consume_task.uid
     *
     * @param uid the value for user_act_consume_task.uid
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_act_consume_task.task_id
     *
     * @return the value of user_act_consume_task.task_id
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_act_consume_task.task_id
     *
     * @param taskId the value for user_act_consume_task.task_id
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_act_consume_task.num
     *
     * @return the value of user_act_consume_task.num
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_act_consume_task.num
     *
     * @param num the value for user_act_consume_task.num
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_act_consume_task.create_time
     *
     * @return the value of user_act_consume_task.create_time
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_act_consume_task.create_time
     *
     * @param createTime the value for user_act_consume_task.create_time
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_act_consume_task.update_time
     *
     * @return the value of user_act_consume_task.update_time
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_act_consume_task.update_time
     *
     * @param updateTime the value for user_act_consume_task.update_time
     * @mbg.generated Wed Dec 12 14:19:09 CST 2018
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public static user newInstance() {
        user u = new user();
        u.setCreateTime(System.currentTimeMillis());
        u.setNum(0);
        u.setTaskId("13");
        u.setUid("324234234234242342324242");
        return u;
    }

}
